'use strict';
module.exports.REDIRECT_URI = 'http://localhost:3000/spotify-callback';
module.exports.COOKIE_STATE = 'juke-to-spotify-converter';

module.exports.TRACKS = [ "Past My Shades (feat. Lupe Fiasco) B.o.B",
    "Make Luv Room 5 Feat. Oliver Cheatham",
    "Get Down Saturday Night Oliver Cheatham",
    "Loving You Is Easy Camo & Krooked",
    "Murder On The Dancefloor (Album Version) Sophie Ellis-Bextor",
    "I Heard It Through The Grapevine Marvin Gaye",
    "Easy Commodores",
    "Little By Little (Caribou RMX) Radiohead",
    "My Love Is Your Love Whitney Houston",
    "Coffee Sylvan Esso",
    "If I Go, Im Goin Gregory Alan Isakov",
    "Home Sweet Home Tommy Lee",
    "Stay With Me Sam Smith",
    "The Birds Telefon Tel Aviv",
    "Twinkle Twinkle Kettel",
    "Power Of Love Dellé",
    "Pump It (Album Version) The Black Eyed Peas",
    "Latch (Acoustic) Sam Smith",
    "Up In The Air (feat. Fran) Oliver Koletzki",
    "Frontin' (Radio Mix/Club Mix) (feat. Jay-Z) Pharrell",
    "September Earth, Wind & Fire",
    "Papa loves mambo Perry Como",
    "Get Free (feat. Amber of Dirty Projectors) Major Lazer",
    "Money On My Mind Sam Smith",
    "Shoulda Jamie Woon",
    "Night Air Jamie Woon",
    "Wicked Game Chris Isaak",
    "Wicked Game (Acoustic) Peter and Kerry",
    "Just All That Shit (Original Mix) FromDropTillDawn",
    "Roof Garden Al Jarreau",
    "Horny (Radio Slave and Thomas Gandey Just 17 Mix) Mousse T.",
    "Horny (Jazz Version) Mousse T.",
    "All About That Bass Meghan Trainor",
    "For Those Who Like To Party Nils Landgren Funk Unit",
    "I'm Gonna Be (500 Miles) The Proclaimers",
    "Turn Down for What DJ Snake & Lil Jon",
    "Holdin' On (Skrillex & Nero Remix) Monsta",
    "Raindrops Keep Falling On My Head B.J. Thomas",
    "Sweat (A La La La La Long) Inner Circle",
    "Drunk in Love (feat. Jay-Z) Beyoncé",
    "Hello Beyoncé",
    "Broken-Hearted Girl Beyoncé",
    "XO Beyoncé",
    "Halo Beyoncé",
    "Thinking Out Loud Ed Sheeran",
    "Thinking Out Loud Ed Sheeran",
    "Survivor Destiny's Child",
    "Brown Sugar D'Angelo",
    "Brown Sugar D'Angelo",
    "Fallin' Alicia Keys",
    "POWER (Album Version (Explicit)) Kanye West",
    "Diamonds Josef Salvat",
    "Where Is The Love? (Album Version) The Black Eyed Peas",
    "Acceptable in the 80's Calvin Harris",
    "I'm So Excited The Pointer Sisters",
    "Mess Around Ray Charles",
    "Leave My Woman Alone Ray Charles",
    "Leave My Woman Alone Ray Charles",
    "Ich Wäre Gern Wie Du Klaus Havenstein",
    "I Wish (Single Edit) Stevie Wonder",
    "Getaway Earth, Wind & Fire",
    "Ain't No Sunshine Al Jarreau",
    "Don't Know Why Norah Jones",
    "Louder Boundzound",
    "Probiers Mal Mit Gemütlichkeit Edgar Ott",
    "King Rodriguez Seeed",
    "Somewhere Beyond the Sea Pianosongs",
    "Papa Noah Seeed",
    "Papa Noah Seeed",
    "Boiling (Dixon Remix) (feat. Sinaed Harnett) Disclosure",
    "I'm A Believer The Monkees",
    "Escape (The Pina Colada Song) Originally Performed By Rupert Holmes [Tribute Version] New Tribute Kings",
    "Real Love Clean Bandit & Jess Glynne",
    "Only One (feat. Paul McCartney) Kanye West",
    "So Demanding Bag Raiders",
    "Howling Frank Wiedemann",
    "Isn't She Lovely (Album Version) Stevie Wonder",
    "Cheerleader (Felix Jaehn Remix Radio Edit) Omi",
    "4 Minutes [feat. Justin Timberlake And Timbaland] Madonna",
    "Spark The Fire (NEW Version) Gwen Stefani",
    "Me & U Cassie"];
/*
    "Anyway You Want (I Can Do It) Final Edition",
    "50 Ways to Leave Your Lover Paul Simon",
    "Maneater Daryl Hall & John Oates",
    "It's My Party Lesley Gore",
    "FourFiveSeconds Rihanna ; Kanye West and Paul McCartney",
    "Almost Home (Sebastien Remix) Moby feat. Damien Jurado",
    "Vergiftet Jan Delay",
    "Something About You Hayden James",
    "Stole the Show (feat. Parson James) Kygo",
    "My Humps (Album Version) The Black Eyed Peas",
    "Herz über Kopf Joris",
    "Mas Que Nada Sergio Mendes",
    "Wenn jetzt Sommer wär (Album Version) Pohlmann.",
    "Wake Me Up When September Ends Green Day",
    "Teenage Crime (Thomas Gold 2012 Rework) Adrian Lux",
    "Papa's Got a Brand New Bag James Brown",
    "Nur für Dich Wise Guys",
    "Wo der Pfeffer wächst Wise Guys",
    "Kompass ohne Norden Prinz Pi",
    "Traffic Lights Lena",
    "Waiting For Love Avicii",
    "Intoxicated (Radio Edit) Martin Solveig and GTA",
    "Hey Mama (feat. Nicki Minaj, Bebe Rexha & Afrojack) David Guetta",
    "Tom's Diner Suzanne Vega",
    "Schoolin' Life Beyoncé",
    "Gatekeeper (Album Version) Feist",
    "Antidote Swedish House Mafia vs. Knife Party",
    "Last Kiss OverDoz.",
    "Greyhound Swedish House Mafia",
    "It's You (Mousse T.'s Discotronic Mix) FCL",
    "Supernatural AlunaGeorge",
    "Holding On Disclosure",
    "Küss mich Madsen",
    "These Walls Kendrick Lamar",
    "Gush Pharrell Williams",
    "You And The Rest Razorlight",
    "60 Thompson Razorlight",
    "The House Razorlight",
    "Freedom Pharrell Williams",
    "Hey Mama (Album Version) The Black Eyed Peas",
    "Cantina Band London Symphony Orchestra;John Williams",
    "Lieblingsmensch Namika",
    "Lieblingsmensch (Übernice Remix) Namika",
    "On Broadway George Benson",
    "Something About Us Daft Punk",
    "Sommer, Sonne, Kaktus! Helge Schneider",
    "Games TCTS",
    "These Heights (Kry Wolf Remix) TCTS",
    "These Heights (Detroit Swindle Mile High Club Remix) TCTS",
    "Trust TCTS",
    "Forward TCTS",
    "Games (Doc Daneeka Remix) (feat. K. Stewart) TCTS",
    "I Don't Know Ruth Brown",
    "Brown Paper Boogie Pimps",
    "No! No! No! No! Axel Boman",
    "No, No, No Part 2 (featuring Wyclef Jean) (#1's Edit) Destiny's Child",
    "Music (feat. Marvin Gaye) Erick Sermon",
    "Ayo Technology (Album Version (Explicit)) 50 Cent",
    "Stairway To Heaven Led Zeppelin",
    "Child In Time Deep Purple",
    "Bohemian Rhapsody (Remastered 2011) Queen",
    "School Supertramp",
    "Choose Your Own Adventure (Kyle Watson Remix) Goldfish",
    "Baby You Can Drive My Car Ben From Corduroy",
    "The Magic Key One-T",
    "Always Like This (Andhim Remix) HVOB",
    "Layla Eric Clapton",
    "Tears In Heaven Eric Clapton",
    "Layla Eric Clapton",
    "Hotel California Eagles",
    "Sound & Color Alabama Shakes",
    "Coming Over (feat. James Hersey) Dillon Francis & Kygo feat. James Hersey",
    "No Diggity Chet Faker",
    "Left Alone feat. Chet Faker (Ta-Ku Remix) Flume",
    "1998 (Roland Tings Remix) Chet Faker",
    "California (Chris Lake & Matroda Remix) (feat. Kaleena Zanders) SNBRN",
    "Signed, Sealed, Delivered (I'm Yours) (Album Version) Stevie Wonder",
    "Wasn't Expecting That Jamie Lawson",
    "It Never Rains in Southern California Albert Hammond",
    "Hotline Bling Drake",
    "Let's Get It On Marvin Gaye",
    "Ventilator Die Orsons",
    "Sympathy For The Devil The Rolling Stones",
    "Love Yourself Justin Bieber",
    "Homecoming (Album Version (Explicit)) Kanye West",
    "Run [I'm A Natural Disaster] Gnarls Barkley",
    "Schwung in die Kiste Die Orsons",
    "Puttin' On The Ritz Robbie Williams",
    "Lose It All KC Lights",
    "Superior Gentleman",
    "Flower Moby",
    "Sweet Caroline Neil Diamond",
    "The Fresh Prince of Bel-Air (Theme from NBC's The Fresh Prince of Bel-Air) DJ Jazzy Jeff & The Fresh Prince",
    "Zieh die Schuh aus Roger Cicero",
    "Virtual Insanity (Remastered) Jamiroquai",
    "Hey There Delilah Plain White T's",
    "Catch & Release (Deepend remix) Matt Simons",
    "Like an Animal RÜFÜS",
    "Clown Emeli Sandé",
    "Brick House (Single Version) Commodores",
    "Picture of My Life Jamiroquai",
    "Falling Jamiroquai",
    "Fill Your Brains Harrison Brome",
    "Strange Adana Twins",
    "Ringo Joris Voorn",
    "Fly Ludovico Einaudi",
    "Einaudi: Una Mattina Ludovico Einaudi",
    "You Sexy Thing Hot Chocolate",
    "Berlin feat. Miss Platnum Modeselektor",
    "Never Leave You - Uh Ooh, Uh Oooh! (Main) Lumidee",
    "1234 Feist",
    "Worry Jack Garratt",
    "Rivers And Roads The Head and the Heart",
    "Sweat RY X",
    "Love Like This RY X",
    "P.I.M.P. (Snoop Dogg Remix (Explicit)) 50 Cent",
    "Body Language (Interpretation) Booka Shade",
    "Body Language M.A.N.D.Y. vs. Booka Shade",
    "Hold On, We're Going Home Drake",
    "My Silver Lining First Aid Kit",
    "Master Pretender First Aid Kit",
    "Nothing Else Matters Lissie",
    "Groove Percussion (feat. Jouliey Bergmann) Tim Baresko",
    "Marilyn Monroe (feat. Room 303) Tim Baresko",
    "Wait M83",
    "Midnight City M83",
    "Singing This Song Cecile",
    "Weathered Jack Garratt",
    "Breathe Life Jack Garratt",
    "Part II (On The Run) Jay Z",
    "Liebe Moop Mama",
    "You're The Top Stacey Kent",
    "That's Not My Name The Ting Tings",
    "Hey Now London Grammar",
    "You Don't Have To (Niconé & Sascha Braemer Remix) dotSTRIPE",
    "Let Me Love You (BBC Introducing Live At SXSW) Jack Garratt",
    "Forest Fires Axel Flovent",
    "Poison (Album Version) Bell Biv DeVoe",
    "Breezy (Album Version (Explicit)) Bell Biv DeVoe",
    "Right Here Jess Glynne",
    "Happy Home (Sam Feldt Remix) ( feat. Lukas Graham) Hedegaard",
    "American Boy [Feat. Kanye West] Album Version) Estelle",
    "Hollow Talk (Lulu Rouge’s Stella Polaris Remix) Choir Of Young Believers",
    "Landslide Robyn Sherwell",
    "50 Shades Of Black Kovacs",
    "I'll Call Thee Hamlet (Live) Woods of Birnam",
    "You And I (Album Version) Medina",
    "Roses (feat. ROZES) The Chainsmokers",
    "I'm Walkin' Fats Domino",
    "Work Rihanna",
    "Bitches N Marijuana (feat. ScHoolboy Q) Chris Brown X Tyga feat. Schoolboy Q",
    "Boom Boom Pow (Album Version) The Black Eyed Peas",
    "Elton John/Rocket Man Elton John",
    "Your Song Elton John",
    "Black And Yellow Wiz Khalifa",
    "Gold Digger (Album Version (Explicit)) Kanye West",
    "How Deep Is Your Love Bee Gees",
    "Night Fever (2007 Remastered Saturday Night Fever Version) Bee Gees",
    "More Than A Woman Bee Gees",
    "Lucifer (Album Version (Explicit)) JAY-Z",
    "Chase The Devil Max Romeo",
    "Geboren Die Fantastischen Vier",
    "Down To The River To Pray (O Brother, Where Art Thou? Soundtrack) Alison Krauss",
    "O Death (O Brother, Where Art Thou? Soundtrack) Ralph Stanley",
    "I Am A Man Of Constant Sorrow (O Brother, Where Art Thou? Soundtrack/Radio Station Version) The Soggy Bottom Boys",
    "Sweet Life (Album Version) Frank Ocean",
    "D.A.N.C.E. Justice",
    "Firefly (feat. Nao) Mura Masa",
    "Inhale Exhale NAO",
    "Apple Cherry NAO" ];*/